import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "../components/context/AuthContext";
import { toast, Toaster, ToastBar } from "react-hot-toast";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeSwitch } from "@/components/theme-switch";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next & Firebase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <ThemeProvider attribute="class" defaultTheme="system">
            <ThemeSwitch />
            {children}
          </ThemeProvider>
        </AuthContextProvider>
        <Toaster position="top-right" reverseOrder={false} />{" "}
      </body>
    </html>
  );
}
